// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "AlluxioService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class AlluxioServiceHandler : virtual public AlluxioServiceIf {
 public:
  AlluxioServiceHandler() {
    // Your initialization goes here
  }

  /**
   * Returns the version of the master service.
   * NOTE: The version should be updated every time a backwards incompatible API change occurs.
   */
  int64_t getServiceVersion() {
    // Your implementation goes here
    printf("getServiceVersion\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<AlluxioServiceHandler> handler(new AlluxioServiceHandler());
  shared_ptr<TProcessor> processor(new AlluxioServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

