/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "block_worker_constants.h"



const block_workerConstants g_block_worker_constants;

block_workerConstants::block_workerConstants() {
}



