/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "block_master_constants.h"



const block_masterConstants g_block_master_constants;

block_masterConstants::block_masterConstants() {
}



