/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef block_worker_CONSTANTS_H
#define block_worker_CONSTANTS_H

#include "block_worker_types.h"



class block_workerConstants {
 public:
  block_workerConstants();

};

extern const block_workerConstants g_block_worker_constants;



#endif
