/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef block_master_CONSTANTS_H
#define block_master_CONSTANTS_H

#include "block_master_types.h"



class block_masterConstants {
 public:
  block_masterConstants();

};

extern const block_masterConstants g_block_master_constants;



#endif
