/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "file_system_worker_constants.h"



const file_system_workerConstants g_file_system_worker_constants;

file_system_workerConstants::file_system_workerConstants() {
}



