/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef file_system_worker_CONSTANTS_H
#define file_system_worker_CONSTANTS_H

#include "file_system_worker_types.h"



class file_system_workerConstants {
 public:
  file_system_workerConstants();

};

extern const file_system_workerConstants g_file_system_worker_constants;



#endif
